### ISSUE TITLE
Upgrade to VFD's instead of relays

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/gate_fw#8]
Especially the left gate (smaller gear) starts very rapidly, resulting in damage over time
A change to a vfd seems appropriate and might fix the following

## advantages
- relay wear (left gate is unreliable because relay not always contacting)
- gear wear 3d printed gear got replaced several times already
- smoother motor start
  - -> more professional
  - less stress overall (on racks and gears...)

## questions
- modbus ?    -> yes 750W vfds already bought
- or control via 2 pins each (fwd, rev is enough)
- control power to vfds      -> required
  -  switch off vfds when idle?
  - gate idles 99% of the time, no need to keep vfds on all the time
- [x] larger cabinet necessary?
- [ ] 3d printed mount for VFDs

## tasks
- [x] turn off both VFDs after certain inactivity
      VFD in idle gets quite warm -> consumes a lot of power when running 24/7  -> turn off when 30min no activity
  - [x] test/measure vfd starting current + time  
  - [x] add powerful relay(s) ?

**Comment by Jonny999999** [comment]
All implemented in V2.0
https://github.com/Jonny999999/gate_fw/releases/tag/V2.0
